### ISSUE TITLE
Address search not working

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#104]
Pointed out by member of the BCTA user test group this morning (March 19, 7:42 am). Confirming I have the same issue.

**Comment by NicoledeGreef** [comment]
@mraross  - address search failing. any geocoder issues at play in Test?

**Comment by mraross** [comment]
geocoder in test is working. Try this to confirm:
https://office.refractions.net/~chodgson/gc/ols-demo/?rt=tst&gc=tst

**Comment by mraross** [comment]
Please ensure all beta testers are using the following link:

https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

**Comment by mraross** [comment]
Even that link doesn't work. Perhaps Ben should investigate?

**Comment by qqnluaq** [comment]
I'm on it

**Comment by mraross** [comment]
Thanks Ben.

**Comment by NicoledeGreef** [comment]
thanks all.

**Comment by qqnluaq** [comment]
fixed, deployed

**Comment by qqnluaq** [comment]
turns out the geocoder `/addresses` endpoint doesn't like the `maxDistance` parameter.

**Comment by mraross** [comment]
@qqnluag To find the nearest address, use this:
https://geocodertst.api.gov.bc.ca/sites/nearest.json?point=-122.377%2C50.121&maxDistance=70000

To find the closest N addresses, use this:
https://geocoder.api.gov.bc.ca/sites/near.json?point=-122.377%2C50.121&maxDistance=70000&maxResults=10

The resource is called sites because a site is a feature that has an address; addresses aren't features, they are properties of a site.

**Comment by gk-tl** [comment]
Thank you for fixing it. Confirming it works again. Also confirming that I'm using the correct link and distributed said link to all beta testers. 

https://bcgov.github.io/smk-tlink/?config=./config/test-services.json

Complete.
