### ISSUE TITLE
Please remove "BETA"

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#135]
![image](https://user-images.githubusercontent.com/59627982/78293785-042f6c80-74de-11ea-8780-7a4132404c13.png)

**Comment by qqnluaq** [comment]
Should I change the version number too?

**Comment by gk-tl** [comment]
Not sure. Deferring to @NicoledeGreef

**Comment by NicoledeGreef** [comment]
I think including the version # somewhere is helpful.  Doesn't have to be exposed in the banner though.  If it was a comment in the source of the banner then we could retrieve it if we're filing an issue report.

Re: version number.  since we are now live (past Beta) should we consider augmenting from 1.0?

**Comment by qqnluaq** [comment]
I can put the version number in the About box.

**Comment by NicoledeGreef** [comment]
Sure - maybe at the very bottom in tiny font?

**Comment by qqnluaq** [comment]
version now in about, and changed to 1.0.0
