### ISSUE TITLE
COV Lot 109 (COVID Layer) - Inactive Link

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#149]
The link under “contact info” for Lot 109 in Vancouver (COVID-19 layer) is inactive. 

![Contact Info COV Lot 109](https://user-images.githubusercontent.com/59627982/83293655-d8102f00-a1a0-11ea-970d-bcf61825b89b.jpg)

**Comment by NicoledeGreef** [comment]
Looking at the Temp parking lot records on the map, I only see contact info for the one near the Port of Vancouver.  How would you like this field represented - wondering if hyperlinked text is desired and if so, what text?  Could be the raw link just hyperlinked or something like "Link"

For the Street View field values I see "Link" followed by a little arrow symbol.

![image](https://user-images.githubusercontent.com/26335003/83294921-ff67fb80-a1a2-11ea-935a-65c0ea5d9ec3.png)

**Comment by gk-tl** [comment]
Same approach as for Streetview would be good.  Thank you.

**Comment by qqnluaq** [comment]
I attached a table [contactinfo.xlsx](https://github.com/bcgov/smk-tlink/files/4713149/contactinfo.xlsx) of the active covid-19 resources that use ContactInfo.
Most of them are phone numbers, but a few are URLs, and a couple of them are weird.
There are a couple of options for formatting this property:
1. Add code to detect the different cases, and format appropriately
1. Add HTML markup to the data, like:
    `<a href="https://foo.com">description</a>`
    **OR**
    `<a href="tel:+18005551234">1 (800) 555 1234</a>`
   so that the contact info is always formatted correctly

**Comment by NicoledeGreef** [comment]
Thanks @qqnluaq . Yes - I see some have phone a phone number and a URL (e.g. Georges Magic Grill in Westbank).  This would make it challenging to format, for sure.

@al-tabb @gk-tl  - do you want to review the formatting of ContactInfo and inject HTML in the data itself (option 2 as in the above comment)  in order to ensure that the formatting comes out correctly?

If we handle it with code then we need to be sure the values supplies are very uniform, e.g. phone number OR a URL is supplied but not both.  It would be ideal if phone numbers were formatted all the same, too.

**Comment by gk-tl** [comment]
Most of the data for the COVID 19 layer comes from other parties (BCTA, MOTI etc). We’re incorporating it into the TRP on an “as is basis”. The exceptions are the parking lot in Vancouver (Lot 109), the lot in North Van, the United Blvd Industrial Area, gravel lot in Maple Ridge (inactive), Scott Rd Park & Ride/North Surrey Sport & Leisure Complex (inactive) and Cloverdale Fairgrounds (inactive). For all others, I suggest we provide the the same link under “Contact Info” as “Info” (ie back to the source of the data). The only contact info that requires a “fix” is Lot 109 in Vancouver. The approach Nicole proposed should work - rename the URL to “Link”.

**Comment by qqnluaq** [comment]
Another option:
3. Separate the phone numbers and the URLs into different fields, like `ContactPhone` and `ContactURL`, and then they can be formatted correctly, and merged into `ContactInfo`

**Comment by gk-tl** [comment]
@al-tabb - please weigh in on how you'd prefer to handle this.

**Comment by NicoledeGreef** [comment]
> Another option:
> 3. Separate the phone numbers and the URLs into different fields, like `ContactPhone` and `ContactURL`, and then they can be formatted correctly, and then merged into a `ContactInfo` field at runtime

I agree this would be the ideal.  It's data model modification and additional integration work at this point though ;)

**Comment by al-tabb** [comment]
I will add the relevant html tags to distinguish phone number links vs web links.  Seems like the easiest solution.

**Comment by NicoledeGreef** [comment]
@al-tabb  - is this data mod still expected or has it been delivered?

**Comment by al-tabb** [comment]
This is now complete.
http://trp.regionalroads.com/api/?data=GM_Covid19Relief&format=geojson&download=true

**Comment by NicoledeGreef** [comment]
@qqnluaq - i think we need to grab this data and incorporate it in order to fix the Contact Info for Georges Magic Grill, for example:

"ContactInfo":"<a href=\"tel:+12504900567\">(250) 490-0567<\/a> <a href=\"http://www.bbfd.ca\" target=\"_blank\">Link<\/a>"

Currently in Test (https://translink-t.apps.gov.bc.ca/trp/) that field generates a 404.

**Comment by NicoledeGreef** [comment]
@gk-tl @al-tabb  Please check latest data in https://bcgov.github.io/smk-tlink/
I have checked Georges in Westbank and it looks good to me.

**Comment by NicoledeGreef** [comment]
Also available in Delivery now: https://translink-d.apps.gov.bc.ca/trp/
browser cache  may need to be cleared in order to pick up the data changes.

**Comment by gk-tl** [comment]
-- Complete. Thank you. --

I checked the contact link for Parking Lot 109 in Vancouver - it works.

I couldn't find another instance of an actual link to an external website (other than the one in Westbank). 

In most cases, the field contains a phone number, like the example below.  

![image](https://user-images.githubusercontent.com/59627982/86168975-c5ee1d00-bacd-11ea-8566-55ebfaf692cd.png)
