### ISSUE TITLE
Expand the options for vehicle types

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#15]
The original beta app built by Translink had a list of vehicle types.  We need to expand the truck types and reflect the provided graphics as appropriate.

**Comment by NicoledeGreef** [comment]
<img width="335" alt="CVRP_vehicle_types" src="https://user-images.githubusercontent.com/26335003/71383224-28e78000-2590-11ea-93d7-af6b50a899bf.PNG">

**Comment by NicoledeGreef** [comment]
Truck icons (SVG format) attached:

[Truck_Icons_for_CVRP.zip](https://github.com/bcgov/smk-tlink/files/3996501/Truck_Icons_for_CVRP.zip)

**Comment by qqnluaq** [comment]
Metadata about truck types:
[configValues_vehicleTypes.js.zip](https://github.com/bcgov/smk-tlink/files/4020604/configValues_vehicleTypes.js.zip)

**Comment by gk-tl** [comment]
Please ensure the default parameters for each vehicle type match the values in the attached EXCEL file (tab 1). Also, "other" and "custom" can be combined. 

![VehPic](https://user-images.githubusercontent.com/59627982/72026314-f1373400-322f-11ea-8c9c-b67c4789ddaf.png)
[2020-01-08 CVRP Vehicle Configurator Defaults.xlsx](https://github.com/bcgov/smk-tlink/files/4037918/2020-01-08.CVRP.Vehicle.Configurator.Defaults.xlsx)

**Comment by gk-tl** [comment]
Vehicle parameters need a little more work. User can only specify whole numbers, but need ability to enter and display value to the second decimal (i.e., Width 2.60 m, Height 4.15 m, Length 12.50 m). Also, when trying to change the values, the app switches to the "Other" category. User should be able to specify different parameters for each vehicle type.

![image](https://user-images.githubusercontent.com/59627982/72546385-8d1ffb80-383f-11ea-8a5d-55dc42cac246.png)

**Comment by qqnluaq** [comment]
Theres a UI semantics problem here. 
What is the role of the Vehicle Type/Axle choices? 
One issue to be aware of is that the route planner API doesn't use the type/axle values, it only cares about the height & weight. So the type/axles operates at present as presets for height & weight (and width & length).
That's why changing the height/weight values to something other than the preset value, will change the type to 'Other', as the height/weight no longer match the type.

If the expectation is to change be able to change the height/weight for a given vehicle type, is the app then expected to retain those values for the next time the app is invoked?

Which leads to another more general question: Should the app remember it's settings from one invocation to the next? It is relatively easy to have the app presist settings on the same browser. Persisting settings across different browsers and/or machines is significantly more difficult.

**Comment by qqnluaq** [comment]
Also, the older demo had support for imperial & metric units for truck parameters. Is that required?

**Comment by gk-tl** [comment]
Thanks for clarifying. A couple of comments:

- While it is true that the vehicle configurator (i.e., vehicle options) primarily influences routing as a function of height and weight, the other parameters also play an important role (at the UI level)

- Any user entered value that exceeds legislated limits should result in a (dotted) red route regardless of whether the route is on a designated truck route or not. Additionally, the app should return a notice/message as follows: 

_Based on the vehicle specifications you entered, you may require a municipal and/or Provincial permit. The driver and/or carrier is responsible for ensuring the default vehicle parameters or user-entered vehicle parameters are an accurate representation of the actual vehicle, for verifying all clearances and restrictions on the route, and for ensuring the vehicle is operated in compliance with all applicable municipal bylaws and provincial and federal regulations. <LINK>Municipal and Provincial contact information</a>"_

- Legislated limits = default values for each vehicle type (that includes axle count - for example, a straight truck with 7 axles is not a "legal" configuration in BC, and would trigger the requirement to obtain a permit to operate on provincial highways and municipal roads. In the TRP this would result in the following behaviour - _display entire generated route as a dotted red line + generate report/notice advising driver a permit may be required._

- Consistent with the above, the app should support user-entered values for each vehicle parameter for all vehicle types. The dimensions parameters should be entered entered to the second decimal place (e.g., Height 4.57 m; Width 3.21 m; Length 22.86 m). Weight and axle count are OK as whole numbers.

- Ability to enter/switch between imperial vs metric is also required (we get a lot drivers coming in from the United States who have no idea of what the metric system is). 

- Please refer to the TL Beta: https://cvrp.translink.ca/

**Comment by qqnluaq** [comment]
If I understand correctly then, the values in https://github.com/bcgov/smk-tlink/blob/develop/vehicle-types.js for each vehicle type/axle should be regarded as the max allowable for that pair? If a larger value is put in it will trigger the warning quoted above, as well as mark the entire route in red. 
Would it be sufficient to have an 'Other' selection in the axle dropdown for the cases when the truck is not a legally defined configuration?

Regarding the metric/imperial distinction, there are lots of uses of distance units in SMK. It would probably make sense to have an application-wide setting for choice of units.

**Comment by gk-tl** [comment]
> Would it be sufficient to have an 'Other' selection in the axle dropdown for the cases when the truck is not a legally defined configuration?

We could add "other" to the axle drop down, but the default values would have to be the max default  weight for the highest axle count. For example, the max legislated weight for a straight truck with 5 axles is 39,200 kg (ignoring logging truck weight allowances, which add another 1,500 kg). Max legal weight for a tractor semi-trailer is 57,100kg

**All other parameters are independent of axle count, except as noted below:**

Max legislated width is 2.6 m (regardless of vehicle type and axle count)
Max legislated height is 4.15 m (regardless of vehicle type and axle count). 

One caveat is that a dump truck with a reg. compliant tarping mechanism gets an additional 15 cm allowance (i.e., 4.30 m). However, this would add complexity to the vehicle configurator, which is why we ignore this allowance for the default vehicle types.

**Length varies depending on vehicle type (regardless of axle count/weight):**

Straight truck 2 axles is 12.50 m, as is a straight truck with 3, 4, or 5 axles. 
Truck and ponly trailer: 23.00 m
Truck and Full Trailer: 25.00 m
A and C-Train: 26.00 m
B-Train: 27.50 m

There are exceptions - max length for a tractor semi-trailer with up to 6 axles is 23.0 m. There are outliers that could be up 23.5 m (single steer, tridem drive, tandem trailer axle). 
Max length for 7 & 8 axle tractor semi-trailers is 23.5 m (assuming a tridem drive axle). 

Buses: 
2 axle max. length is 12.50 m (same as a straight truck)
3 axle max length is 14.00 m

**Comment by gk-tl** [comment]
Thank you for addressing the noted issues. A couple of minor tweaks/suggestions:

- GVW should be a whole number (no need for first decimal)
- User can only type  a whole number for Height, Width, and Length, but should be able to type the entire value rather than using the +/- toggle to provide the decimals. It is much easier to type "4.88" m than type 4 and toggle to 0.88.
- The triggers for the blue vs red dotted line should be as follows:

Height <=4.15 --> Blue
Height > 4.15 m --> Dotted Red (currently, 4.16 m shows as a blue line, 4.17 m switched to dotted red)

Width <= 2.60 m --> Blue
Width > 2.60 m -->  Dotted Red (same issue as with Height)

Length <= Default value (e.g., 12.50 m) --> Blue
Length > default value (e.g., 12.50 m) --> Dotted Red (same issue as with Height)

**Comment by gk-tl** [comment]
Thank you. Nearly complete. However, I will create a new card for the remaining issue:

> User can only type a whole number for Height, Width, and Length, but should be able to type the entire value rather than using the +/- toggle to provide the decimals. It is much easier to type "4.88" m than type 4 and toggle to 0.88.

**Comment by NicoledeGreef** [comment]
Closing this as @gk-tl  has now created #54 to track remaining items.
