### ISSUE TITLE
Route disappears when a different tool is invoked

### ISSUE THREAD

**Issue by cpspicer** [bcgov/smk-tlink#18]
If you generate a route, then access the base maps to toggle, the route is erased.  Not a huge issue since routing is so fast, but might annoy some

**Comment by qqnluaq** [comment]
This is a general behaviour in SMK. The layers specific to a particular tool are only visible when that tool is active.

**Comment by gk-tl** [comment]
Thank you for flagging this/looking into it.

I noticed the same thing happens when you want to use the "identify" tool to, for example, look up the height of a structure on a generated route. Am I correct in assuming it may not be possible to show a generated route when using the "identify" tool?

Example - user would like to look up the height clearance for the two overhead structures on Kingsway.
![image](https://user-images.githubusercontent.com/59627982/72113387-25285d00-32f5-11ea-8fbe-7ddf24e1b6e5.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq - can you please provide an estimate for this one?

**Comment by qqnluaq** [comment]
I propose modifying the directions tool so that the route stays visible even when the tool isn't active.
This may have an effect on #34 .
I estimate 8 hours.

**Comment by NicoledeGreef** [comment]
This is helpful.  Ideally the route should stay on the map despite which widget is subsequently invoked.  It should only disappear when the Reset button is clicked in the Directions widget.

**Comment by gk-tl** [comment]
Complete. Thank you.
