### ISSUE TITLE
related to #204; add in DLV and TST Geoserver instances

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#210]
With an eye towards implementation of the requests in GH Issue #204, we inquired if Translink is hosting an “integration” version of the database/Geoserver that we can hit from the non-Production instances of the app so that data changes can be verified in Delivery and/or Test before the data changes go to Production.

The dev and staging API endpoints are https://devapi.regionalroads.com and https://stgapi.regionalroads.com respectively.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - please review, ask any clarification questions and provide ballpark estimate

**Comment by qqnluaq** [comment]
We need to ensure that the configuration for each environment includes all the endpoints that are necessary. It looks like the deployment configuration would need to be modified to support a DLV and TST instance. 
The app would need to be changed so that environment config is isolated to one file, and each instance gets its own version of the file. This is about 2 days work.
The deployment for the app also needs to be updated to support multiple instances. I don't know how long that would take. Probably the people who worked on the deployment script would have a better idea.
