### ISSUE TITLE
Dangerous Good Routes layer

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#28]
Data provision is anticipated on January 24th.

@al-tabb to send us screen shots of desired symbolization (desired colour/symbol); as well it would be good to confirm the display name, where it should be placed in the layer list, draw order concerns.

**Comment by NicoledeGreef** [comment]
In addition to data, please provide:
Display Name,
Where the layer should appear in the layer list
Draw order
Desired colour/symbols

**Comment by al-tabb** [comment]
-Data has been provided to Nicole.
-Display Name: Dangerous Goods Eligible Route
-This layer should appear underneath Truck Advisories and Restrictions in the layer list.
-This layer should underneath the Truck Routes/Truck Advisories and Restrictions layer.
-The suggested symbology is a wide black and yellow dotted line (so that it is visible underneath the Truck Route layer when they are both visible):
![image](https://user-images.githubusercontent.com/59742145/73763829-d967a880-4726-11ea-9c6b-aa93a1c9bf82.png)

**Comment by NicoledeGreef** [comment]
For reference: GM_DangerousGoodsRoutes in the GDB

**Comment by qqnluaq** [comment]
I'll need the attribute formatting if this layer is to be identified against.
Is this layer loaded into AGOL? or in some other location?

**Comment by al-tabb** [comment]
This layer is not in AGOL.  I previously sent it to Nicole.  I just forwarded it on to you.  Let me know if you have any questions once you have a look at the dataset.

**Comment by NicoledeGreef** [comment]
@qqnluaq  - i'll forward the ZIP files via email.

**Comment by al-tabb** [comment]
@NicoledeGreef @qqnluaq Revised datasets have been sent by email.

**Comment by qqnluaq** [comment]
@al-tabb:
It's possible I missed it, but i don't see any tickets related to the disposition of the `GM_DangerousGoodsRestrictions` layer. Is this layer to be included on map?

Also, still waiting on word on attribute configuration for `GM_DangerousGoodsRoutes`

**Comment by al-tabb** [comment]
@qqnluaq Sorry for the confusion.  We have replaced the GM_DangerousGoodsRestrictions layer with the GM_DangerousGoodsRoutes layer.  We were originally going to show all Dangerous Goods Restrictions but decided it is clearer to just show the dangerous goods routes.

**Comment by al-tabb** [comment]
The attributes should be:
Route Type (DangerousGoodType)
Municipality (Municipality)
Link (DangerousGoodsLink)
Notes (DangerousGoodsNotes)

**Comment by gk-tl** [comment]
Complete. Thank you.
