### ISSUE TITLE
Oversize/Overweight Vehicle Routes layer

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-tlink#29]
Data provision is anticipated on January 24th.

@al-tabb to send us screen shots of desired symbolization (desired colour/symbol); as well it would be good to confirm the display name, where it should be placed in the layer list, draw order concerns.

**Comment by NicoledeGreef** [comment]
In addition to data, please provide:
Display Name,
Where the layer should appear in the layer list
Draw order
Desired colour/symbols

**Comment by al-tabb** [comment]
This layer should be comprised of 5 sub-layers under the heading OS/OW Route which can be toggled on/off individually:
-4.88m Height Pre-Screened Route
(WHERE Height_Restriction = 4.88)
-5.0m Width Pre-Screened Route
(WHERE Width_Restriction = 5.0)
-80,000kg GVW Pre-Screened Route
(WHERE Weight_Restriction = 80000)
-85,000kg GVW Pre-Screened Route
(WHERE Height_Restriction = 85000)
-125,000 GVW Pre-Screened Route
(WHERE Height_Restriction = 125000)

-This layer (and sub-layers) should appear below Dangerous Goods Routes in the layer list.
-This layer should appear underneath Truck Route, Truck Advisories & Restrictions.

Suggested symbology (thick line so that it is visible underneath Truck Routes/Truck Advisories & Restrictions when both are toggled on):
![image](https://user-images.githubusercontent.com/59742145/73765191-0cab3700-4729-11ea-9052-7cf46c4a9781.png)

**Comment by NicoledeGreef** [comment]
For reference: GM_OSOWRoutes in the GDB

**Comment by gk-tl** [comment]
The OS-OW Vehicle Route Layer should be comprised of 6 layers, as follows:

**Oversize-Overweight (OS-OW) Vehicle Routes** [Parent Heading]
- Term Permit Routes   
     - Sub-layers -- see card #30
- Overall Height (OAH) up to 4.88 m 
- Overall Width (OAW) up to 5.00 m
- Gross Vehicle Weight (GVW) up to 80,000 kg
- Gross Vehicle Weight (GVW) up to 85,000 kg
- Gross Vehicle Weight (GVW) up to 125,000 kg

Colour/symbology as per Alan's comments (thick lines etc)

Display name as above (i.e., "Term Permit Routes", "Overall Height (OAH) up to 4.88 m" etc)

Layer should be positioned following "Temporary Road Closures"

When the parent heading is selected:

- The "Term Permit Route" route layer, the "Overhead structures with height marker", "Overhead structures without height marker",  "Truck advisories and restrictions", and "Temporary road closures" layers should be selected by default. 

- The "Truck routes" layer should be toggled off. If user selects it, toggle off all OS-OW Vehicle Layers   (i.e., the term permit layer and if user selected any of the other, also those).

**Comment by gk-tl** [comment]
@NicoledeGreef and @qqnluaq - please hold off doing further work on this card and card #29. Alan is going to revise the data sets based on my comments and resubmit.

**Comment by al-tabb** [comment]
@NicoledeGreef @qqnluaq Revised data has been sent by email.

**Comment by qqnluaq** [comment]
Took a best guess at attributes for these layers.
Automatic layer toggling not implemented (yet)

**Comment by gk-tl** [comment]
Complete - looks great. Thank you.
